//! JSON-RPC 2.0 wire types for codex app-server.
//!
//! Codex's app-server protocol is JSON-RPC 2.0 over stdio. The schemas
//! are auto-generated by `codex app-server generate-json-schema`. We
//! model only the subset of types we exchange:
//!
//!   * Outgoing requests we send: `initialize`, `thread/start`,
//!     `thread/resume`, `turn/start`. (Outgoing notifications:
//!     `initialized`.)
//!   * Incoming responses we read: keep them as raw `serde_json::Value`
//!     and pluck out `result.thread.id` after `thread/start|resume` —
//!     no other field matters in v1.
//!   * Incoming notifications: only the subset that maps to an
//!     `AgentEvent`. All others are silently dropped.
//!
//! Wire shape verified against codex CLI v0.125.0.

use serde::Serialize;

// ──────────────────────────────────────────────────────────────────────
// Outgoing
// ──────────────────────────────────────────────────────────────────────

#[derive(Debug, Serialize)]
pub(crate) struct OutgoingRequest<'a, P> {
    pub jsonrpc: &'static str,
    pub id: i64,
    pub method: &'a str,
    pub params: P,
}

impl<'a, P: Serialize> OutgoingRequest<'a, P> {
    pub(crate) fn new(id: i64, method: &'a str, params: P) -> Self {
        Self {
            jsonrpc: "2.0",
            id,
            method,
            params,
        }
    }
}

#[derive(Debug, Serialize)]
pub(crate) struct OutgoingNotification<'a, P> {
    pub jsonrpc: &'static str,
    pub method: &'a str,
    pub params: P,
}

impl<'a, P: Serialize> OutgoingNotification<'a, P> {
    pub(crate) fn new(method: &'a str, params: P) -> Self {
        Self {
            jsonrpc: "2.0",
            method,
            params,
        }
    }
}

#[derive(Debug, Serialize)]
pub(crate) struct InitializeParams<'a> {
    #[serde(rename = "clientInfo")]
    pub client_info: ClientInfo<'a>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ClientInfo<'a> {
    pub name: &'a str,
    pub title: &'a str,
    pub version: &'a str,
}

#[derive(Debug, Serialize)]
pub(crate) struct ThreadStartParams<'a> {
    /// `"never"` disables all approval round-trips so codex runs
    /// fire-and-forget (matches the implicit `exec --json` behavior).
    #[serde(rename = "approvalPolicy")]
    pub approval_policy: &'a str,
    pub cwd: &'a str,
    /// `"danger-full-access"` lets codex execute commands and edit
    /// files without per-action gating.
    pub sandbox: &'a str,
}

#[derive(Debug, Serialize)]
pub(crate) struct ThreadResumeParams<'a> {
    #[serde(rename = "threadId")]
    pub thread_id: &'a str,
    #[serde(rename = "approvalPolicy")]
    pub approval_policy: &'a str,
    pub cwd: &'a str,
    pub sandbox: &'a str,
}

#[derive(Debug, Serialize)]
pub(crate) struct TurnStartParams<'a> {
    #[serde(rename = "threadId")]
    pub thread_id: &'a str,
    pub input: Vec<TurnInput<'a>>,
    #[serde(rename = "approvalPolicy")]
    pub approval_policy: &'a str,
    pub cwd: &'a str,
    // Note: sandboxPolicy here is an internally-tagged object
    // (oneOf {dangerFullAccess|readOnly|externalSandbox|workspaceWrite})
    // not a string. We omit it entirely and let the per-turn policy
    // fall back to the thread's `sandbox` field configured at
    // thread/start. Add it back as a typed enum if v2 needs per-turn
    // overrides.
}

#[derive(Debug, Serialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub(crate) enum TurnInput<'a> {
    #[serde(rename = "text")]
    Text { text: &'a str },
}

#[derive(Debug, Serialize)]
pub(crate) struct InitializedParams {}

// ──────────────────────────────────────────────────────────────────────
// Incoming
// ──────────────────────────────────────────────────────────────────────

// We don't define typed incoming wrappers: the spawn driver parses
// each line as `serde_json::Value` and dispatches by presence of `id`
// (response) vs `method` (notification). Notification param shapes
// that we read fields off of live in `projector.rs`.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn outgoing_request_serializes_with_jsonrpc_field() {
        let req = OutgoingRequest::new(
            0,
            "initialize",
            InitializeParams {
                client_info: ClientInfo {
                    name: "anatta",
                    title: "anatta",
                    version: "0.1.0",
                },
            },
        );
        let s = serde_json::to_string(&req).unwrap();
        assert!(s.contains("\"jsonrpc\":\"2.0\""));
        assert!(s.contains("\"method\":\"initialize\""));
        assert!(s.contains("\"clientInfo\""));
    }
}
